# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vk.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 580)
        MainWindow.setMinimumSize(QtCore.QSize(900, 580))
        MainWindow.setMaximumSize(QtCore.QSize(900, 580))
        font = QtGui.QFont()
        font.setFamily("Sans")
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/main_icon/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(-5, 0, 911, 591))
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("background-color: #ccffcc;")
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setStyleSheet("")
        self.tab.setObjectName("tab")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(15, 460, 370, 70))
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(13)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setStyleSheet("border-radius: 12px; background-color:#ADD8E6;")
        self.groupBox_2.setObjectName("groupBox_2")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_2.setGeometry(QtCore.QRect(30, 31, 150, 27))
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(13)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setChecked(True)
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_3.setGeometry(QtCore.QRect(161, 32, 120, 27))
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(13)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setChecked(False)
        self.radioButton_3.setObjectName("radioButton_3")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setGeometry(QtCore.QRect(15, 290, 370, 160))
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(13)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setStyleSheet("border-radius: 12px; background-color:#ADD8E6;")
        self.groupBox_3.setObjectName("groupBox_3")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox.setGeometry(QtCore.QRect(20, 35, 240, 27))
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(13)
        self.checkBox.setFont(font)
        self.checkBox.setStyleSheet("")
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_2.setGeometry(QtCore.QRect(20, 65, 240, 27))
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(13)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_4 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_4.setGeometry(QtCore.QRect(20, 99, 240, 27))
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(13)
        self.checkBox_4.setFont(font)
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_5 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_5.setGeometry(QtCore.QRect(20, 132, 240, 27))
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(13)
        self.checkBox_5.setFont(font)
        self.checkBox_5.setObjectName("checkBox_5")
        self.btn_start_scrape = QtWidgets.QPushButton(self.tab)
        self.btn_start_scrape.setGeometry(QtCore.QRect(450, 430, 410, 100))
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.btn_start_scrape.setFont(font)
        self.btn_start_scrape.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.btn_start_scrape.setMouseTracking(True)
        self.btn_start_scrape.setStyleSheet("QPushButton#btn_start_scrape\n"
"{\n"
"border-radius: 25px; \n"
"background-color:#20B2AA;\n"
"}\n"
"QPushButton::hover#btn_start_scrape\n"
"{\n"
"background-color : lightgreen;\n"
"}\n"
"")
        self.btn_start_scrape.setObjectName("btn_start_scrape")
        self.progress_bar_id_scrape = QtWidgets.QProgressBar(self.tab)
        self.progress_bar_id_scrape.setGeometry(QtCore.QRect(420, 50, 460, 70))
        self.progress_bar_id_scrape.setStyleSheet("QProgressBar#progress_bar_id_scrape\n"
"{\n"
"border: solid grey;\n"
"border-radius: 15px;\n"
"color: white;\n"
"text-align:center;\n"
"background-color: #ff6600\n"
"}\n"
"QProgressBar::chunk#progress_bar_id_scrape\n"
"{\n"
"background-color: #05B8CC;\n"
"border-radius :15px;\n"
"}    ")
        self.progress_bar_id_scrape.setProperty("value", 0)
        self.progress_bar_id_scrape.setObjectName("progress_bar_id_scrape")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_4.setGeometry(QtCore.QRect(14, 210, 370, 60))
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setStyleSheet("border-radius: 12px; background-color:#ADD8E6;")
        self.groupBox_4.setObjectName("groupBox_4")
        self.radioButton_4 = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_4.setGeometry(QtCore.QRect(30, 31, 130, 27))
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.radioButton_4.setFont(font)
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton_5 = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_5.setGeometry(QtCore.QRect(161, 32, 100, 27))
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.radioButton_5.setFont(font)
        self.radioButton_5.setChecked(True)
        self.radioButton_5.setObjectName("radioButton_5")
        self.line = QtWidgets.QFrame(self.tab)
        self.line.setGeometry(QtCore.QRect(390, 10, 16, 510))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_3 = QtWidgets.QFrame(self.tab)
        self.line_3.setGeometry(QtCore.QRect(427, 264, 430, 40))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.progress_bar_data_scrape = QtWidgets.QProgressBar(self.tab)
        self.progress_bar_data_scrape.setGeometry(QtCore.QRect(430, 190, 450, 70))
        self.progress_bar_data_scrape.setStyleSheet("QProgressBar#progress_bar_data_scrape\n"
"{\n"
"border: solid grey;\n"
"border-radius: 15px;\n"
"color: white;\n"
"text-align:center;\n"
"background-color: #ff6600\n"
"}\n"
"QProgressBar::chunk#progress_bar_data_scrape\n"
"{\n"
"background-color: #05B8CC;\n"
"border-radius :15px;\n"
"}    ")
        self.progress_bar_data_scrape.setProperty("value", 0)
        self.progress_bar_data_scrape.setObjectName("progress_bar_data_scrape")
        self.progress_bar_file_scrape = QtWidgets.QProgressBar(self.tab)
        self.progress_bar_file_scrape.setGeometry(QtCore.QRect(430, 340, 450, 70))
        self.progress_bar_file_scrape.setStyleSheet("QProgressBar#progress_bar_file_scrape\n"
"{\n"
"border: solid grey;\n"
"border-radius: 15px;\n"
"color: white;\n"
"text-align:center;\n"
"background-color: #ff6600\n"
"}\n"
"QProgressBar::chunk#progress_bar_file_scrape\n"
"{\n"
"background-color: #05B8CC;\n"
"border-radius :15px;\n"
"}    ")
        self.progress_bar_file_scrape.setProperty("value", 0)
        self.progress_bar_file_scrape.setObjectName("progress_bar_file_scrape")
        self.line_4 = QtWidgets.QFrame(self.tab)
        self.line_4.setGeometry(QtCore.QRect(430, 120, 420, 30))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(420, 0, 400, 31))
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(420, 150, 470, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(430, 290, 361, 30))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.groupBox_11 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_11.setGeometry(QtCore.QRect(10, 20, 380, 180))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_11.setFont(font)
        self.groupBox_11.setStyleSheet("border-radius: 12px; background-color:#ADD8E6;")
        self.groupBox_11.setObjectName("groupBox_11")
        self.line_edit_domain_scrape = QtWidgets.QLineEdit(self.groupBox_11)
        self.line_edit_domain_scrape.setGeometry(QtCore.QRect(21, 40, 340, 40))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(14)
        self.line_edit_domain_scrape.setFont(font)
        self.line_edit_domain_scrape.setStyleSheet("background-color:#FDF5E6")
        self.line_edit_domain_scrape.setObjectName("line_edit_domain_scrape")
        self.line_edit_token_scrape = QtWidgets.QLineEdit(self.groupBox_11)
        self.line_edit_token_scrape.setGeometry(QtCore.QRect(20, 130, 340, 40))
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(13)
        self.line_edit_token_scrape.setFont(font)
        self.line_edit_token_scrape.setStyleSheet("background-color:#FDF5E6")
        self.line_edit_token_scrape.setObjectName("line_edit_token_scrape")
        self.label_14 = QtWidgets.QLabel(self.groupBox_11)
        self.label_14.setGeometry(QtCore.QRect(100, 90, 191, 21))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 30, 410, 230))
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(14)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setStyleSheet("border-radius: 12px; background-color:#ADD8E6;")
        self.groupBox_5.setObjectName("groupBox_5")
        self.line_edit_domain_ml = QtWidgets.QLineEdit(self.groupBox_5)
        self.line_edit_domain_ml.setGeometry(QtCore.QRect(21, 50, 350, 40))
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(13)
        self.line_edit_domain_ml.setFont(font)
        self.line_edit_domain_ml.setStyleSheet("background-color:#FDF5E6")
        self.line_edit_domain_ml.setObjectName("line_edit_domain_ml")
        self.line_edit_token_ml = QtWidgets.QLineEdit(self.groupBox_5)
        self.line_edit_token_ml.setGeometry(QtCore.QRect(20, 170, 360, 40))
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(13)
        self.line_edit_token_ml.setFont(font)
        self.line_edit_token_ml.setStyleSheet("background-color:#FDF5E6")
        self.line_edit_token_ml.setObjectName("line_edit_token_ml")
        self.label = QtWidgets.QLabel(self.groupBox_5)
        self.label.setGeometry(QtCore.QRect(90, 110, 240, 50))
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btn_analyze_ml = QtWidgets.QPushButton(self.tab_2)
        self.btn_analyze_ml.setGeometry(QtCore.QRect(10, 270, 410, 120))
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(15)
        self.btn_analyze_ml.setFont(font)
        self.btn_analyze_ml.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.btn_analyze_ml.setStyleSheet("QPushButton#btn_analyze_ml\n"
"{\n"
"border-radius: 25px; \n"
"background-color:#20B2AA;\n"
"}\n"
"QPushButton:hover#btn_analyze_ml\n"
"{\n"
"   background-color:lightgreen;\n"
"}")
        self.btn_analyze_ml.setObjectName("btn_analyze_ml")
        self.line_7 = QtWidgets.QFrame(self.tab_2)
        self.line_7.setGeometry(QtCore.QRect(450, 250, 400, 20))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.label_11 = QtWidgets.QLabel(self.tab_2)
        self.label_11.setGeometry(QtCore.QRect(440, 20, 459, 50))
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(13)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.progress_bar_data_ml = QtWidgets.QProgressBar(self.tab_2)
        self.progress_bar_data_ml.setGeometry(QtCore.QRect(450, 190, 430, 60))
        self.progress_bar_data_ml.setStyleSheet("QProgressBar#progress_bar_data_ml\n"
"{\n"
"border: solid grey;\n"
"border-radius: 15px;\n"
"color: white;\n"
"text-align:center;\n"
"background-color: #ff6600\n"
"}\n"
"QProgressBar::chunk#progress_bar_data_ml\n"
"{\n"
"background-color: #05B8CC;\n"
"border-radius :15px;\n"
"}    ")
        self.progress_bar_data_ml.setProperty("value", 0)
        self.progress_bar_data_ml.setObjectName("progress_bar_data_ml")
        self.label_12 = QtWidgets.QLabel(self.tab_2)
        self.label_12.setGeometry(QtCore.QRect(440, 150, 430, 31))
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(13)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.progress_bar_file_ml = QtWidgets.QProgressBar(self.tab_2)
        self.progress_bar_file_ml.setGeometry(QtCore.QRect(450, 460, 430, 60))
        self.progress_bar_file_ml.setStyleSheet("QProgressBar#progress_bar_file_ml\n"
"{\n"
"border: solid grey;\n"
"border-radius: 15px;\n"
"color: white;\n"
"text-align:center;\n"
"background-color: #ff6600\n"
"}\n"
"QProgressBar::chunk#progress_bar_file_ml\n"
"{\n"
"background-color: #05B8CC;\n"
"border-radius :15px;\n"
"}    ")
        self.progress_bar_file_ml.setProperty("value", 0)
        self.progress_bar_file_ml.setObjectName("progress_bar_file_ml")
        self.label_13 = QtWidgets.QLabel(self.tab_2)
        self.label_13.setGeometry(QtCore.QRect(440, 420, 430, 31))
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(13)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.line_8 = QtWidgets.QFrame(self.tab_2)
        self.line_8.setGeometry(QtCore.QRect(449, 130, 430, 20))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.label_15 = QtWidgets.QLabel(self.tab_2)
        self.label_15.setGeometry(QtCore.QRect(440, 270, 510, 40))
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(13)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.progress_bar_bot_ml = QtWidgets.QProgressBar(self.tab_2)
        self.progress_bar_bot_ml.setGeometry(QtCore.QRect(450, 320, 430, 60))
        self.progress_bar_bot_ml.setStyleSheet("QProgressBar#progress_bar_bot_ml\n"
"{\n"
"border: solid grey;\n"
"border-radius: 15px;\n"
"color: white;\n"
"text-align:center;\n"
"background-color: #ff6600\n"
"}\n"
"QProgressBar::chunk#progress_bar_bot_ml\n"
"{\n"
"background-color: #05B8CC;\n"
"border-radius :15px;\n"
"}    ")
        self.progress_bar_bot_ml.setProperty("value", 0)
        self.progress_bar_bot_ml.setObjectName("progress_bar_bot_ml")
        self.line_9 = QtWidgets.QFrame(self.tab_2)
        self.line_9.setGeometry(QtCore.QRect(450, 380, 430, 30))
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.progress_bar_real_percentage_ml = QtWidgets.QProgressBar(self.tab_2)
        self.progress_bar_real_percentage_ml.setGeometry(QtCore.QRect(20, 460, 390, 60))
        self.progress_bar_real_percentage_ml.setStyleSheet("QProgressBar#progress_bar_real_percentage_ml\n"
"{\n"
"border: solid grey;\n"
"border-radius: 15px;\n"
"color: white;\n"
"text-align:center;\n"
"background-color: red\n"
"}\n"
"QProgressBar::chunk#progress_bar_real_percentage_ml\n"
"{\n"
"background-color: #05B8CC;\n"
"border-radius :15px;\n"
"}    ")
        self.progress_bar_real_percentage_ml.setProperty("value", 0)
        self.progress_bar_real_percentage_ml.setObjectName("progress_bar_real_percentage_ml")
        self.label_16 = QtWidgets.QLabel(self.tab_2)
        self.label_16.setGeometry(QtCore.QRect(10, 410, 410, 50))
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(13)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.line_2 = QtWidgets.QFrame(self.tab_2)
        self.line_2.setGeometry(QtCore.QRect(427, 30, 10, 500))
        self.line_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_2.setLineWidth(3)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setObjectName("line_2")
        self.progress_bar_id_ml = QtWidgets.QProgressBar(self.tab_2)
        self.progress_bar_id_ml.setGeometry(QtCore.QRect(450, 68, 430, 60))
        self.progress_bar_id_ml.setStyleSheet("QProgressBar#progress_bar_id_ml\n"
"{\n"
"border: solid grey;\n"
"border-radius: 15px;\n"
"color: white;\n"
"text-align:center;\n"
"background-color: #ff6600\n"
"}\n"
"QProgressBar::chunk#progress_bar_id_ml\n"
"{\n"
"background-color: #05B8CC;\n"
"border-radius :15px;\n"
"}    ")
        self.progress_bar_id_ml.setProperty("value", 0)
        self.progress_bar_id_ml.setObjectName("progress_bar_id_ml")
        self.tabWidget.addTab(self.tab_2, "")
        self.widget = QtWidgets.QWidget()
        self.widget.setObjectName("widget")
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setGeometry(QtCore.QRect(180, 230, 550, 90))
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(17)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color: rgb(15, 243, 220);\n"
"border-radius: 15px;")
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_2.setGeometry(QtCore.QRect(180, 100, 550, 90))
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(17)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("background-color: rgb(15, 243, 220);\n"
"border-radius: 15px;")
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.tabWidget.addTab(self.widget, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "VK_Smm by @Limitedonly41 v.1.4.5"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Парсить мобильные номера?"))
        self.radioButton_2.setText(_translate("MainWindow", "Да"))
        self.radioButton_3.setText(_translate("MainWindow", "Нет"))
        self.groupBox_3.setTitle(_translate("MainWindow", " Парсить социальные сети?"))
        self.checkBox.setText(_translate("MainWindow", "Instagram"))
        self.checkBox_2.setText(_translate("MainWindow", "Skype"))
        self.checkBox_4.setText(_translate("MainWindow", "Facebook"))
        self.checkBox_5.setText(_translate("MainWindow", "Twitter"))
        self.btn_start_scrape.setText(_translate("MainWindow", "Начать парсинг"))
        self.groupBox_4.setTitle(_translate("MainWindow", "     Парсить ссылки на сайт?"))
        self.radioButton_4.setText(_translate("MainWindow", "Да"))
        self.radioButton_5.setText(_translate("MainWindow", "Нет"))
        self.label_3.setText(_translate("MainWindow", "Сбор id участников группы"))
        self.label_4.setText(_translate("MainWindow", "Сбор данных об участниках группы"))
        self.label_5.setText(_translate("MainWindow", "Формирование файла"))
        self.groupBox_11.setTitle(_translate("MainWindow", "  Введите ссылку или id группы"))
        self.line_edit_domain_scrape.setPlaceholderText(_translate("MainWindow", "https://vk.com/"))
        self.label_14.setText(_translate("MainWindow", "Введите токен"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Парсинг данных вк"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Введите ссылку или id группы"))
        self.line_edit_domain_ml.setPlaceholderText(_translate("MainWindow", "https://vk.com/"))
        self.label.setText(_translate("MainWindow", "Введите токен"))
        self.btn_analyze_ml.setText(_translate("MainWindow", "Начать анализ группы"))
        self.label_11.setText(_translate("MainWindow", "Сбор id участников группы"))
        self.label_12.setText(_translate("MainWindow", "Сбор данных об участниках группы"))
        self.label_13.setText(_translate("MainWindow", "Формирование файла"))
        self.label_15.setText(_translate("MainWindow", "Определение ботов среди участников"))
        self.label_16.setText(_translate("MainWindow", "Процент реальных пользователей"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Анализ группы"))
        self.lineEdit.setText(_translate("MainWindow", "email:   limitedonly41@gmail.com"))
        self.lineEdit_2.setText(_translate("MainWindow", "      tg:   @Limitedonly41"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.widget), _translate("MainWindow", "Контакты"))
import res_rc
